import { EmbedBuilder, InteractionContextType, SlashCommandBuilder } from 'discord.js';
import type Command from '../interfaces/command.js';

export default {
  data: new SlashCommandBuilder()
    .setName('help')
    .setDescription("Information about any of Quabos's commands.")
    .setContexts([InteractionContextType.Guild, InteractionContextType.BotDM])
    .addStringOption(option =>
      option
        .setName('command')
        .setDescription('The command to get help for.')
        .setRequired(false)
        .setAutocomplete(true),
    ),
  usage: '/help [command]',
  execute: async interaction => {
    const client = interaction.client;
    const avatarURL =
      client.user.avatarURL({ size: 4096, extension: 'png' }) || client.user.defaultAvatarURL;
    const helpEmbed = new EmbedBuilder().setAuthor({
      name: client.user.tag,
      iconURL: avatarURL,
    });

    const commandName = interaction.options.getString('command', false) ?? 'help';
    const command = client.commands.get(commandName);

    if (commandName === 'help' || !command) {
      helpEmbed
        .setDescription(
          '**' +
            client.user.username +
            ' is an entertainment focused bot! It can learn from messages sent in your server and generate new ones with plenty of customization.**\n\nYou can start by typing `/config channels add [channel]` in order to collect messages from a specific channel. As more messages are collected, the result will be better! You can also force a message to be generated by using `/generate`, and you can check how many messages have been collected with `/info server`.',
        )
        .setThumbnail(avatarURL);

      await interaction.reply({ embeds: [helpEmbed] });
      return;
    }

    const usage: string[] = [];
    if (command.subcommands) {
      const subcommandUsages = Object.values(command.subcommands).map(
        subcommand => subcommand.usage,
      );
      usage.push(...subcommandUsages);
    } else if (command.usage) {
      usage.push(command.usage);
    }

    helpEmbed
      .setTitle(`Command: /${commandName}`)
      .setDescription(
        `**Description**:\n${command.data.description}\n\n**Usage**:\n${usage.join('\n')}`,
      );

    await interaction.reply({ embeds: [helpEmbed], flags: 'Ephemeral' });
  },
  autocomplete: async interaction => {
    const focusedValue = interaction.options.getFocused().toLowerCase().trim();

    const filteredCommands = interaction.client.commands
      .filter(command => command.data.name.startsWith(focusedValue))
      .map(command => ({ name: command.data.name, value: command.data.name }));

    await interaction.respond(filteredCommands);
  },
} satisfies Command;
