import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navigation } from './ui/Navigation';
import { NightSky } from './ui/NightSky';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Quabos | Discord Bot',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[linear-gradient(0deg,_rgba(24,18,24,1)_40%,_rgba(50,4,89,1)_100%)] min-h-screen text-white space-y-10 md:space-y-20 lg:space-y-24`}
      >
        <NightSky />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
